version: '3.8'

services:
  app:
    build:
    ports:
    - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
  image: postgres:15
  enviroment: 
    POSTGRES_DB: books_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - 5432:5432
  volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: